CREATE TABLE posts (
    id INT AUTO_INCREMENT, 
    user_id TEXT, 
    post_id INT UNSIGNED NOT NULL DEFAULT 0, 
    picture TEXT,
    text TEXT,
    assignment_point INT UNSIGNED NOT NULL DEFAULT 0, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY (id)
     );